version: '2'
catalog:
  name: "Gophish"
  version: "v0.6-rancher3"
  description: "Open source phishing toolkit"
  minimum_rancher_version: v0.51.0
  questions:
    - variable: http_enabled
      description: "Enable HTTP public port"
      label: "Enable public port. Disable it if you use a LB"
      type: "boolean"
      default: "true"
    - variable: http_port
      description: "Public port to access Gophish web UI"
      label: "HTTP public port"
      required: true
      default: "80"
      type: "int"
    - variable: mgmt_port
      description: "Management port (by default, 3333/tcp)"
      label: "Management port"
      required: true
      default: "3333"
      type: "int" 
    - variable: volume_driver
      description: "Volume driver to use with this service"
      label: "Volume driver"
      required: true
      default: "local"
      type: enum
      options:
        - local
        - rancher-nfs
        - rancher-efs
        - rancher-ebs
